# type name of this configuration
type: B

# basic setting parameters
clip_length: 5.0 # [sec]

# preprocessing parameters
sample_rate: 44100
hop_length: 441
n_fft: 2048
n_mels: 64
f_min: 0
f_max: 22050

# test parameters
bs: 64 #128
mixup: 0.4
n_folds: 5
epochs: 300
finetune_epochs: 20
aug: RCxSA # RC: random resized crop, SA: spec augment
model: R18 # R18: ResNetish18, VGG: VGGish

# dataset configurations
data_root: /data/A/2018fsd